id: IBD996148
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T20:43:06+00:00'
last_modified: '2022-06-08T05:58:45.999572+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG6198
  title: འཚུབ་མ་ཁེར་རྐྱང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    FFF7:
      image_group_id: I1KG6232
      title: ''
      total_pages: 290
      order: 1
      base_file: FFF7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
